### ISSUE TITLE
CLI options definitions were upgraded with "type"

### ISSUE THREAD

**Issue by cvargas-xbrein** [qwantix/serverless-athena#11]
Try to deploy but give me this error : 
 
```
  athena:
    catalog: AwsDataCatalog #optional (default: AwsDataCatalog)
    databases: # list of your dbs
      - name: qa_cannibalization # required, your database name, do not use an existing database, will be dropped in deployement process
        catalog: AwsDataCatalog #optional (default: AwsDataCatalog)
        output: s3://aws-athena-query-results-958531303673-us-east-1/ # required, your results bucket
        description: Default db for ${self:service} api project  # optional, table comment
        properties: # optional, db properties
          - author: serverless
        tables: # list of your tables
          - name: qa_table # required, table name
            ddl: $(file(resources/athena/qa_table.sql)} # required, DDL containing the CREATE TABLE
            keepPartitions: true # force backup and restore partitions
```

```
CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
 - ServerlessAthenaPlugin for "database", "table
```
